### ISSUE TITLE
Solution to fix compiler errors (DIP25)

### ISSUE THREAD

**Issue by SuperDIMMaX** [godot-d/godot-d#77]
Problem with returning `ref T foo() {return this.X}`
change to `ref T foo() return {return this.X}`
example:
`	ref Vector3 opIndex(int axis)
	{
		return this.elements[axis];
	}
`
to
`	ref Vector3 opIndex(int axis)
	return {
		return this.elements[axis];
	}
`
and this compiles with no errors

**Comment by sheepandshepherd** [comment]
Thanks, this is (finally) fixed in d554c00 and v0.1.10.
