### ISSUE TITLE
GodotInitOptions.in_editor contains strange value

### ISSUE THREAD

**Issue by MANKEYYENAME** [godot-d/godot-d#80]
In the editor, it is 1107806977. Otherwise, a random number. Windows 10, godot v 3.2.3

**Comment by MANKEYYENAME** [comment]
I looked at these numbers in binarom representation and the first 8 least significant bits are correct. Maybe godot_bool is 1 byte?

**Comment by sheepandshepherd** [comment]
You're right, it should be 1 byte. I guess implementation-defined, but all the current C and C++ compilers use `sizeof(bool)` = 1, like D's `bool`. Fixed in the `v0.1.11` release
