### ISSUE TITLE
Compile error caused by empty import path

### ISSUE THREAD

**Issue by ishax-kos** [godot-d/godot-d#81]
`godot-d\util\pregenerate\app.d(153)`  causes a compile error if `importPath` is not included in the dub file. Perhaps have it check `sourcePaths` as well?

**Comment by sheepandshepherd** [comment]
Good idea, scanning the source files would be the correct behavior anyway.

Dub doesn't pass `sourcePaths` itself to preGenerateCommands, but it seems to properly add files from the paths to `sourceFiles` before passing that variable on, so I can use it.

Fixed in `v0.1.11`/`v0.1.12`.
